name: Deploy React App to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    # Step 3: Install dependencies and build the project
    - name: Install dependencies
      run: npm install

    - name: Build the React app
      run: npm run build

    # Step 4: Deploy to EC2 instance using SSH
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          # Navigate to home directory
          cd ~

          # Check if the project directory exists
          if [ -d "react-actions" ]; then
            echo "Repository already exists, pulling latest changes..."
            cd react-actions
            git pull origin main
          else
            echo "Cloning repository for the first time..."
            git clone https://github.com/your-username/react-actions.git
            cd react-actions
          fi

          # Install Node.js and pm2 if not already installed
          if ! command -v node &> /dev/null; then
            echo "Node.js not found, installing..."
            curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
            sudo apt install -y nodejs
          fi

          if ! command -v pm2 &> /dev/null; then
            echo "pm2 not found, installing..."
            sudo npm install -g pm2
          fi

          # Install dependencies and build the project
          npm install
          npm run build

          # Restart the application using pm2
          pm2 restart react-app || pm2 start npm --name "react-app" -- run start
          pm2 save
